<template>
  <div class="wrapper">
    <img
      v-for="(img, index) in props.images"
      :src="`src/assets/${img}`"
      alt=""
      :id="`ab-${index}`"
      :key="index"
      :class="activeIndex === index ? 'fade-in' : 'fade-out'"
    />
  </div>
</template>

<script setup>
import { ref, watch, onMounted, onBeforeUnmount } from "vue";
const props = defineProps(["images"]);

const activeIndex = ref(0);

let interval = null;

onMounted(() => {
  interval = setInterval(() => {
    activeIndex.value++;
    if (activeIndex.value === 3) {
      activeIndex.value = 0;
    }
  }, 2000);
});

onBeforeUnmount(() => {
  clearInterval(interval);
});
</script>

<style scoped>
.wrapper {
  width: 100%;
  height: 100%;
  position: relative;
  overflow: hidden;
}
img {
  width: 100vw;
  height: auto;
  position: absolute;
  top: 0px;
  left: 0px;
}
.fade-in {
  -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-6-8 10:50:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

.fade-out {
  -webkit-animation: fade-out 1s ease-out both;
  animation: fade-out 1s ease-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-6-8 10:51:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-out
 * ----------------------------------------
 */
@-webkit-keyframes fade-out {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
@keyframes fade-out {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}

@media only screen and (max-width: 768px) {
  img {
    width: auto;
    height: 100vh;
  }
}
</style>
