<template>
  <div class="wrapper bg-pan-right">
    <div class="overlay"></div>
    <div class="content">
      <Container>
        <div class="col5">
          <div style="display: inline-block">
            <Typography variant="h2" mode="light">Our Facilities</Typography>
            <div class="borderBottomRed"></div>
          </div>
          <Typography variant="p" mode="light">
            Perusahaan penyedia jasa prima, handal, baik dan profesional serta memiliki
            standard nasional dan terpercaya.</Typography
          >
          <Typography variant="span" mode="light">Pelajari lebih lanjut</Typography>
        </div>

        <div class="col5">
          <img :src="Satpam" alt="" style="width: 100%; height: auto" class="display" />
        </div>
      </Container>
    </div>
  </div>
</template>

<script setup>
import Typography from "./Typography.vue";
import Container from "./Container.vue";
import TriangleCornerImage from "./TriangleCornerImage.vue";
import Satpam from "../assets/gambar1.png";

function alertMe() {
  alert("ok");
}
</script>

<style scoped>
.borderBottomRed {
  width: 100%;
  border-bottom: 3px solid red;
  margin-top: 3px;
}
.wrapper {
  background-image: url("../assets/facilities.png");
  position: relative;
  padding-bottom: 80px;
  padding-top: 80px;
}
.imgPerspective {
  width: 100%;
  height: auto;
}

.overlay {
  position: absolute;
  top: 0px;
  left: 0px;
  width: 100%;
  height: 100%;
  background-color: #020b4a;
  opacity: 0.9;
}
.content {
  position: relative;
  z-index: 10;
}
.col5 {
  display: inline-block;
  padding: 15px;
  box-sizing: border-box;
  width: 50%;
  vertical-align: top;
}

.display {
  -moz-box-shadow: 0px 0px 300px 100px rgba(255, 0, 100, 0.4);
  -webkit-box-shadow: 0px 0px 300px 100px rgba(255, 0, 100, 0.4);
  box-shadow: 0px 0px 300px 100px rgba(255, 0, 100, 0.4);
  border: 1px solid rgba(255, 0, 100, 1);
}

@media only screen and (max-width: 768px) {
  .col5 {
    width: 100%;
  }
}
.bg-pan-right {
  -webkit-animation: bg-pan-right 32s infinite both;
  animation: bg-pan-right 32s infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-6-11 14:27:18
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bg-pan-right
 * ----------------------------------------
 */
@-webkit-keyframes bg-pan-right {
  0% {
    background-position: 0% 50%;
  }
  100% {
    background-position: 100% 50%;
  }
}
@keyframes bg-pan-right {
  0% {
    background-position: 0% 50%;
  }
  100% {
    background-position: 100% 50%;
  }
}
</style>
