<template>
  <div class="wrapper">
    <!-- <div class="bg-wrapper">
      <slot name="background"></slot>
    </div> -->
    <!--     <div class="overlay">
      <slot name="content"></slot>
    </div>-->
    <div class="dynamic">
      <slot name="dynamic"></slot>
    </div>
  </div>
</template>

<script setup></script>

<style scoped>
.wrapper {
  width: 100%;
  min-height: 800px;
  position: relative;
}

.bg-wrapper {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0px;
  left: 0px;
  z-index: -1;
}

.dynamic {
  position: absolute;
  top: 0px;
  left: 0px;
  z-index: 3;
  width: 100%;
  height: 100%;
}

.overlay {
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0px;
  left: 0px;
  z-index: 1;
}

.color-change-2x {
  -webkit-animation: color-change-2x 2s linear alternate both;
  animation: color-change-2x 2s linear alternate both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-7-1 10:5:49
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation color-change-2x
 * ----------------------------------------
 */
@-webkit-keyframes color-change-2x {
  0% {
    background: rgba(0, 0, 0, 1);
  }
  100% {
    background: navy;
  }
}
@keyframes color-change-2x {
  0% {
    background: rgba(0, 0, 0, 1);
  }
  100% {
    background: navy;
  }
}
</style>
