<template>
  <div class="hero-wrapper">
    <!-- picture viewer -->
    <Container style="position: relative; height: 100%">
      <ThreedDPicViewer @changeBackground="changeBackground($event)" />
    </Container>

    <!-- main text -->
    <div class="hero-text">
      <Container noPadding>
        <div class="col-4">
          <Typography variant="h1" mode="light"
            >The Most Reliable Service Provider</Typography
          >
          <Typography variant="p" mode="light">
            Perusahaan penyedia jasa prima, handal, baik dan profesional serta memiliki
            standard nasional dan terpercaya.
          </Typography>
        </div>
      </Container>
    </div>

    <!-- background -->
    <div class="hero-bg" :style="{ 'background-image': `url(${selectedBg})` }">
      <div
        style="width: 100%; height: 100%; background-color: #020b4a; opacity: 0.8"
      ></div>
    </div>

    <!-- decor -->
    <div class="hero-bg-decor" style="top: 0px; left: 0px"></div>
    <div class="hero-bg-decor" style="bottom: 0px; right: 0px"></div>

    <!-- line decor -->
    <div class="hero-line-decor"></div>

    <!-- desktop menu -->
    <slot name="desktopmenu"></slot>
  </div>
</template>

<script setup>
import { ref } from "vue";
import ThreedDPicViewer from "./ThreedDPicViewer.vue";
import Container from "./Container.vue";
import Typography from "./Typography.vue";
import defaultBg from "../assets/cleaningservice.png";

const selectedBg = ref(defaultBg);

function changeBackground(e) {
  selectedBg.value = e;
}
</script>

<style scoped>
.hero-wrapper {
  background-color: navy;
  width: 100%;
  height: 900px;
  overflow: hidden;
  position: relative;
}

.hero-text {
  position: absolute;
  top: 0px;
  width: 100%;
  top: 20%;
  z-index: 4;
  color: #ffffff;
}

.hero-bg {
  position: absolute;
  top: 0px;
  left: 0px;
  width: 100%;
  height: 100%;
  background-size: contain;
  z-index: 1;
  /* Add the blur effect */
  filter: blur(8px);
  -webkit-filter: blur(8px);
}

.hero-bg-decor {
  position: absolute;
  z-index: 2;
  box-shadow: 0px 0px 300px 300px rgba(255, 0, 100, 0.2);
}

.hero-line-decor {
  position: absolute;
  width: 30%;
  height: 30%;
  border: 3px solid rgba(255, 0, 100, 1);
  z-index: 1;
  top: 35%;
  left: 58%;
  margin-left: -15%;
  -webkit-animation: images-entry-scale 1s linear alternate both;
  animation: images-entry-scale 1s linear alternate both;
}

.kenburns-top {
  -webkit-animation: kenburns-top 5s ease-out infinite alternate both;
  animation: kenburns-top 5s ease-out infinite alternate both;
}

.col-4 {
  width: 40%;
  box-sizing: border-box;
  padding: 15px;
  display: inline-block;
  vertical-align: middle;
}

.col-8 {
  width: 80%;
  box-sizing: border-box;
  padding: 15px;
  display: inline-block;
  vertical-align: middle;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-7-3 12:45:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation kenburns-top
 * ----------------------------------------
 */
@-webkit-keyframes kenburns-top {
  0% {
    -webkit-transform: scale(1) translateY(0);
    transform: scale(1) translateY(0);
    -webkit-transform-origin: 50% 16%;
    transform-origin: 50% 16%;
  }
  100% {
    -webkit-transform: scale(1.25) translateY(-15px);
    transform: scale(1.25) translateY(-15px);
    -webkit-transform-origin: top;
    transform-origin: top;
  }
}
@keyframes kenburns-top {
  0% {
    -webkit-transform: scale(1) translateY(0);
    transform: scale(1) translateY(0);
    -webkit-transform-origin: 50% 16%;
    transform-origin: 50% 16%;
  }
  100% {
    -webkit-transform: scale(1.25) translateY(-15px);
    transform: scale(1.25) translateY(-15px);
    -webkit-transform-origin: top;
    transform-origin: top;
  }
}

@keyframes images-entry-scale {
  0% {
    width: 0%;
    height: 0%;
  }
  50% {
    width: 0%;
    height: 30%;
  }
  100% {
    width: 30%;
    height: 30%;
  }
}

@-webkit-keyframes images-entry-scale {
  0% {
    width: 0%;
    height: 0%;
  }
  50% {
    width: 0%;
    height: 30%;
  }
  100% {
    width: 30%;
    height: 30%;
  }
}
</style>
