<template>
  <!-- Hero -->
  <Hero>
    <template v-slot:background>
      <div
        :style="{
          backgroundImage: `url(${bgImg})`,
          width: '100%',
          height: '100%',
        }"
      ></div>
      <!-- <AnimatedBackground :images="images" /> -->
    </template>
    <template #content>
      <div class="temp">
        <nav>
          <Container>
            <ul>
              <li>
                <img
                  src="./assets/sip-transparent.png"
                  alt=""
                  style="width: 80px; height: auto"
                />
              </li>
              <li>
                <TopMenuItem text="Home" />
              </li>
              <li>
                <TopMenuItem text="About" />
              </li>
              <li>
                <TopMenuItem text="Service" />
              </li>
              <li>
                <TopMenuItem text="Facilities" />
              </li>
              <li>
                <TopMenuItem text="Legal" />
              </li>
              <li>
                <TopMenuItem text="Contact" />
              </li>
            </ul>
          </Container>
        </nav>

        <div class="content">
          <Container>
            <div style="box-sizing: border-box; padding-top: 20px">
              <div class="col-6">
                <Typography variant="h1" mode="light"
                  >The Most Reliable Service Provider</Typography
                >
                <Typography variant="p" mode="light">
                  Perusahaan penyedia jasa prima, handal, baik dan profesional serta
                  memiliki standard nasional dan terpercaya.
                </Typography>
              </div>
              <div class="col-4" style="text-align: right">
                <img class="big-hero-img" src="./assets/hero-bordered-2.png" alt="" />
                <div class="small-hero-img">
                  <div>
                    <img src="./assets/sip-employee.png" alt="" />
                  </div>
                  <div>
                    <img
                      src="./assets/gambar1.png"
                      alt=""
                      style="position: relative; right: 460px; bottom: 70px"
                    />
                  </div>
                </div>
              </div>
              <div style="text-align: center; margin-top: 50px">
                <img
                  src="./assets/images/arrow_downward_24px.svg"
                  alt=""
                  class="shake-vertical"
                  style="position: relative"
                />
              </div>
            </div>
          </Container>
        </div>
      </div>
    </template>
  </Hero>

  <!-- services list -->
  <div style="margin-bottom: 80px">
    <Section1>
      <ServiceSection />
    </Section1>
  </div>

  <!-- legal -->
  <div style="margin-bottom: 80px">
    <FacilitiesSection />
  </div>
</template>

<script setup>
import "./assets/base.css";
import AnimatedBackground from "./components/AnimatedBackground.vue";
import Hero from "./components/Hero.vue";
import { ref } from "vue";
import Button from "./components/Button.vue";
import Bg from "./assets/tile_background.png";
import TopMenuItem from "./components/TopMenuItem.vue";
import Section1 from "./components/Section1.vue";
import ServiceSection from "./components/ServiceSection.vue";
import FacilitiesSection from "./components/FacilitiesSection.vue";
import Container from "./components/Container.vue";
import Typography from "./components/Typography.vue";
import ThreedBox from "./components/ThreedBox.vue";

const images = ref(["ar1.jpg", "sip1.png", "sip2.png"]);
const bgImg = ref(Bg);
const bottomDivIndex = ref(-1);

function showBottomDiv(num) {
  bottomDivIndex.value = num;
}

function hideBottomDiv(num) {
  bottomDivIndex.value = 0;
}
</script>

<style scoped>
.borderBottomRed {
  border-bottom: 3px solid red;
  margin-top: 3px;
}

ul {
  display: flex;
  justify-content: right;
  align-items: center;
  margin: 0px;
  box-sizing: border-box;
  padding: 10px;
}

ul li {
  padding-top: 15px;
  margin: 10px 20px 10px 0px;
  /** text-transform: uppercase; **/
  list-style-type: none;
  cursor: pointer;
}

.col-6 {
  width: 60%;
  box-sizing: border-box;
  padding: 15px;
  display: inline-block;
  vertical-align: middle;
}

.col-4 {
  width: 40%;
  box-sizing: border-box;
  padding: 15px;
  display: inline-block;
  vertical-align: middle;
}

.big-hero-img {
  width: auto;
  height: 500px;
}

.small-hero-img {
  display: none;
}

.small-hero-img div {
  display: inline-block;
  box-sizing: border-box;
  width: 50%;
  overflow: hidden;
  height: 250px;
}

ul li:first-child {
  margin-right: auto;
}

ul li:last-child {
  margin-right: 0px;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-5-24 16:42:49
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-vertical
 * ----------------------------------------
 */

.shake-vertical {
  -webkit-animation: shake-vertical 8s cubic-bezier(0.455, 0.03, 0.515, 0.955) infinite
    both;
  animation: shake-vertical 8s cubic-bezier(0.455, 0.03, 0.515, 0.955) infinite both;
}

@-webkit-keyframes shake-vertical {
  0%,
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }

  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
  }

  20%,
  40%,
  60% {
    -webkit-transform: translateY(8px);
    transform: translateY(8px);
  }

  80% {
    -webkit-transform: translateY(6.4px);
    transform: translateY(6.4px);
  }

  90% {
    -webkit-transform: translateY(-6.4px);
    transform: translateY(-6.4px);
  }
}

@keyframes shake-vertical {
  0%,
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }

  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
  }

  20%,
  40%,
  60% {
    -webkit-transform: translateY(8px);
    transform: translateY(8px);
  }

  80% {
    -webkit-transform: translateY(6.4px);
    transform: translateY(6.4px);
  }

  90% {
    -webkit-transform: translateY(-6.4px);
    transform: translateY(-6.4px);
  }
}

@media only screen and (max-width: 768px) {
  .col-4,
  .col-6 {
    width: 100%;
  }

  ul {
    display: none;
  }

  .big-hero-img {
    display: none;
  }

  .small-hero-img {
    display: block;
  }
}

/** very small device screen **/
@media only screen and (max-width: 400px) {
  .small-hero-img div:first-child img {
    top: 20px;
  }
}
</style>
